### ISSUE TITLE
Uncaught R3F hooks can only be used within the Canvas component

### ISSUE THREAD

**Issue by gregdingle** [RenaudRohlinger/r3f-perf#29]
After upgrading to 5.4.2, I got the error 
```
Uncaught R3F hooks can only be used within the Canvas component
```
![image](https://user-images.githubusercontent.com/28797/155202167-497b51ef-a12b-4f9b-821b-4c710cbdc570.png)

I haven't investigated anymore yet.

**Comment by gregdingle** [comment]
Ok I see that the https://github.com/utsuboco/r3f-perf#usage has changed.

**Comment by gregdingle** [comment]
I reread https://docs.pmnd.rs/react-three-fiber/api/hooks and I spent some time debugging but I can't see why the hooks inside r3f-perf won't work inside our `Canvas`

**Comment by RenaudRohlinger** [comment]
Hello @gregdingle. I tried both in a Canvas and in the DOM to use the `headless` mode and everything works properly I have also the `Calls` information that seemed to miss in your previous issue. 

Here is a working example of usePerf() using 5.4.2:
https://codesandbox.io/s/perlin-cubes-r3f-perf-headless-mh1jl7?file=/src/App.js

Also, I would strongly recommend cleaning your node modules and doing a fresh npm install.

If it still does not work an example would be very helpful. 

Otherwise, the UI and performances of the tool have greatly improved if you want to give it a try:
https://codesandbox.io/s/perlin-cubes-r3f-perf-wtp9t?file=/src/App.js

**Comment by gregdingle** [comment]
@RenaudRohlinger  I discovered the cause is in version incompatibility. If you upgrade r3f and react to the next major version you can repro as in [this sandbox example](https://codesandbox.io/s/perlin-cubes-r3f-perf-headless-forked-kisozm?file=/src/App.js). 

We use the latest versions in prod for react concurrent support.

**Comment by RenaudRohlinger** [comment]
See #25
